# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            CODE SALSA
tagline:          'Its good for you.'
description:      'A fresh mix of ideas, projects, and spicy bits of inspiration.'
url:              http://eriksorensen.github.io

author:
  name:           'ESSORENSEN'
  url:            https://eriksorensen.github.io

paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/eriksorensen/eriksorensen.github.io

# Disqus
disqus:
  shortname:      essorensen
