# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            johnnylambada
tagline:          'Thoughts on development, politics, raising kids and life.'
description:      'John is a professional developer specializing in Android.'
url:              http://johnnylambada.com

author:
  name:           'John Lombardo'
  url:            https://johnnylambada

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/johnnylambada/johnnylambada.github.io

# Disqus
disqus:
  shortname:      johnnylambada
